# @package _global_
model:
  _target_: remfx.models.FXClassifier
  lr: 3e-4
  lr_weight_decay: 1e-3
  sample_rate: ${sample_rate}
  network:
    _target_: remfx.classifier.Cnn14
    num_classes: ${num_classes}
    n_fft: 1024
    hop_length: 256
    n_mels: 128
    sample_rate: 44100
    model_sample_rate: 44100
    specaugment: False