# @package _global_

effects:
  chorus:
      _target_: remfx.effects.RandomPedalboardChorus
      sample_rate: ${sample_rate}
      min_depth: 0.2
      min_mix: 0.3
  distortion:
      _target_: remfx.effects.RandomPedalboardDistortion
      sample_rate: ${sample_rate}
      min_drive_db: 10
      max_drive_db: 50
  compressor:
      _target_: remfx.effects.RandomPedalboardCompressor
      sample_rate: ${sample_rate}
      min_threshold_db: -42.0
      max_threshold_db: -20.0
      min_ratio: 1.5
      max_ratio: 6.0
  reverb:
      _target_: remfx.effects.RandomPedalboardReverb
      sample_rate: ${sample_rate}
      min_room_size: 0.3
      max_room_size: 1.0
      min_damping: 0.2
      max_damping: 1.0
      min_wet_dry: 0.2
      max_wet_dry: 0.8
      min_width: 0.2
      max_width: 1.0
  delay:
      _target_: remfx.effects.RandomPedalboardDelay
      sample_rate: ${sample_rate}
      min_delay_seconds: float = 0.1,
      max_delay_sconds: float = 1.0,
      min_feedback: float = 0.05,
      max_feedback: float = 0.6,
      min_mix: float = 0.2,
      max_mix: float = 0.7,