# @package _global_
effects:
  train_effects:
      Chorus:
        _target_: remfx.effects.RandomPedalboardChorus
        sample_rate: ${sample_rate}
      Distortion:
        _target_: remfx.effects.RandomPedalboardDistortion
        sample_rate: ${sample_rate}
        min_drive_db: -10
        max_drive_db: 50
      Compressor:
        _target_: remfx.effects.RandomPedalboardCompressor
        sample_rate: ${sample_rate}
        min_threshold_db: -42.0
        max_threshold_db: -20.0
        min_ratio: 1.5
        max_ratio: 6.0
      Reverb:
        _target_: remfx.effects.RandomPedalboardReverb
        sample_rate: ${sample_rate}
        min_room_size: 0.3
        max_room_size: 1.0
        min_damping: 0.2
        max_damping: 1.0
        min_wet_dry: 0.2
        max_wet_dry: 0.8
        min_width: 0.2
        max_width: 1.0
  val_effects:
      Chorus:
        _target_: remfx.effects.RandomPedalboardChorus
        sample_rate: ${sample_rate}
        min_rate_hz: 1.0
        max_rate_hz: 1.0
        min_depth: 0.3
        max_depth: 0.3
        min_centre_delay_ms: 7.5
        max_centre_delay_ms: 7.5
        min_feedback: 0.4
        max_feedback: 0.4
        min_mix: 0.4
        max_mix: 0.4
      Distortion:
        _target_: remfx.effects.RandomPedalboardDistortion
        sample_rate: ${sample_rate}
        min_drive_db: 30
        max_drive_db: 30
      Compressor:
        _target_: remfx.effects.RandomPedalboardCompressor
        sample_rate: ${sample_rate}
        min_threshold_db: -32
        max_threshold_db: -32
        min_ratio: 3.0
        max_ratio: 3.0
        min_attack_ms: 10.0
        max_attack_ms: 10.0
        min_release_ms: 40.0
        max_release_ms: 40.0
      Reverb:
        _target_: remfx.effects.RandomPedalboardReverb
        sample_rate: ${sample_rate}
        min_room_size: 0.5
        max_room_size: 0.5
        min_damping: 0.5
        max_damping: 0.5
        min_wet_dry: 0.4
        max_wet_dry: 0.4
        min_width: 0.5
        max_width: 0.5
