# @package _global_
effects:
  train_effects:
      Chorus:
        _target_: remfx.effects.RandomPedalboardChorus
        sample_rate: ${sample_rate}
  val_effects:
      Chorus:
        _target_: remfx.effects.RandomPedalboardChorus
        sample_rate: ${sample_rate}
        min_rate_hz: 1.0
        max_rate_hz: 1.0
        min_depth: 0.3
        max_depth: 0.3
        min_centre_delay_ms: 7.5
        max_centre_delay_ms: 7.5
        min_feedback: 0.4
        max_feedback: 0.4
        min_mix: 0.4
        max_mix: 0.4