# @package _global_
effects:
  train_effects:
      Compressor:
        _target_: remfx.effects.RandomPedalboardCompressor
        sample_rate: ${sample_rate}
        min_threshold_db: -42.0
        max_threshold_db: -20.0
        min_ratio: 1.5
        max_ratio: 6.0
  val_effects:
      Compressor:
        _target_: remfx.effects.RandomPedalboardCompressor
        sample_rate: ${sample_rate}
        min_threshold_db: -32
        max_threshold_db: -32
        min_ratio: 3.0
        max_ratio: 3.0
        min_attack_ms: 10.0
        max_attack_ms: 10.0
        min_release_ms: 40.0
        max_release_ms: 40.0