# @package _global_
effects:
  train_effects:
      Distortion:
        _target_: remfx.effects.RandomPedalboardDistortion
        sample_rate: ${sample_rate}
        min_drive_db: -10
        max_drive_db: 50
  val_effects:
      Distortion:
        _target_: remfx.effects.RandomPedalboardDistortion
        sample_rate: ${sample_rate}
        min_drive_db: 25
        max_drive_db: 25