# @package _global_
effects:
  Reverb:
    _target_: remfx.effects.RandomPedalboardReverb
    sample_rate: ${sample_rate}
    min_room_size: 0.3
    max_room_size: 1.0
    min_damping: 0.2
    max_damping: 1.0
    min_wet_dry: 0.2
    max_wet_dry: 0.8
    min_width: 0.2
    max_width: 1.0
