# @package _global_
defaults:
  - override /model: demucs
  - override /effects: all
seed: 12345
sample_rate: 48000
chunk_size: 262144 # 5.5s
logs_dir: "./logs"
render_root: "/scratch/EffectSet"
accelerator: "gpu"
log_audio: True
# Effects
num_kept_effects: [0,0] # [min, max]
num_removed_effects: [0,5] # [min, max]
shuffle_kept_effects: True
shuffle_removed_effects: True
num_classes: 5
effects_to_keep:
effects_to_remove:
  - distortion
  - compressor
  - reverb
  - chorus
  - delay
datamodule:
  batch_size: 16
  num_workers: 8

ckpts:
  RandomPedalboardDistortion: "ckpts/demucs_distortion.ckpt"
  RandomPedalboardCompressor: "ckpts/demucs_compressor.ckpt"
  RandomPedalboardReverb: "ckpts/demucs_reverb.ckpt"
  RandomPedalboardChorus: "ckpts/demucs_chorus.ckpt"
  RandomPedalboardDelay: "ckpts/demucs_delay.ckpt"
inference_effects_ordering:
  - "RandomPedalboardDistortion"
  - "RandomPedalboardCompressor"
  - "RandomPedalboardReverb"
  - "RandomPedalboardChorus"
  - "RandomPedalboardDelay"
num_bins: 1025