# @package _global_
defaults:
  - override /model: demucs
  - override /effects: all
seed: 12345
sample_rate: 48000
chunk_size: 262144 # 5.5s
logs_dir: "./logs"
render_root: "/scratch/EffectSet"
accelerator: "gpu"
log_audio: True
# Effects
num_kept_effects: [0,0] # [min, max]
num_removed_effects: [0,5] # [min, max]
shuffle_kept_effects: True
shuffle_removed_effects: True
num_classes: 5
effects_to_keep:
effects_to_remove:
  - distortion
  - compressor
  - reverb
  - chorus
  - delay
datamodule:
  batch_size: 1
  num_workers: 8
  train_dataset: None
  val_dataset: None
  test_dataset:
    _target_: remfx.datasets.InferenceDataset
    root: ${oc.env:DATASET_ROOT}
    sample_rate: ${sample_rate}
ckpts:
  RandomPedalboardDistortion: "ckpts/demucs_distortion_aug.ckpt"
  RandomPedalboardCompressor: "ckpts/demucs_compressor_aug.ckpt"
  RandomPedalboardReverb: "ckpts/demucs_reverb_aug.ckpt"
  RandomPedalboardChorus: "ckpts/demucs_chorus_aug.ckpt"
  RandomPedalboardDelay: "ckpts/demucs_delay_aug.ckpt"
inference_effects_ordering:
  - "RandomPedalboardDistortion"
  - "RandomPedalboardCompressor"
  - "RandomPedalboardReverb"
  - "RandomPedalboardChorus"
  - "RandomPedalboardDelay"
num_bins: 1025