# @package _global_
defaults:
  - override /model: umx
  - override /effects: all
seed: 12345
sample_rate: 48000
chunk_size: 262144 # 5.5s
logs_dir: "./logs"
render_files: True
render_root: "./data"
accelerator: null
log_audio: True
# Effects
max_kept_effects: -1
max_removed_effects: -1
shuffle_kept_effects: True
shuffle_removed_effects: False
num_classes: 5
effects_to_use:
  - compressor
  - distortion
  - reverb
  - chorus
  - delay
effects_to_remove:
  - compressor
  - distortion
  - reverb
  - chorus
  - delay
datamodule:
  batch_size: 16
  num_workers: 8